# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# what branch we are watching
trigger:
  - 'master'

pool: 
  vmImage: ubuntu-latest

#name a variable
variables:
- name: 'person'
  value: 'me'
pr: 'none'

#groups sequential actions
stages:
  - stage:
    jobs: 
      - job: 'build'
        steps:
          - script: 'dotnet build VendorApp/VendorApp.csproj'
          - script: echo "oh hey $(person)"
      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: 'dotnet test VendorApp/VendorApp.csproj'
      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: 'dotnet publish VendorApp/VendorApp.csproj'

name: '$(date:yyyMMdd)$(rev:r)'